### ISSUE TITLE
Define "online only" dboes category

### ISSUE THREAD

**Issue by grenwi** [Leibniz-HBI/DBoeS-Automatization#53]
What should be considered as online only medium for the dboes 2.0?

One option would be to count frequencies to domain links, categorize news media within the set of most frequently linked domains, and consider the top N (or all above M links wihtin a certain time period) as relevant public speakers.

Alternatively, we use collected lists from external sources (eg. fake news schleidern from mimikama.at).

**Comment by FlxVctr** [comment]
External sources might also be rankings such as by Alexa: https://www.alexa.com/topsites/countries/DE
