### ISSUE TITLE
identify and acknowledge contributors

### ISSUE THREAD

**Issue by janhinrikschmidt** [Leibniz-HBI/DBoeS-Automatization#55]
many people have contributed to the DBÖS since 2015; we should think about a suitable place for acknowledging their work

Lisa Merten
Christoph Beyer
Isabelle Petrich
Stella Mickeler Garcia
Leonie Krug
Torben Steenbuck
Karl Kriemann
Louisa Pröschel
Leonard Just
Katharina Johnsen

**Comment by FlxVctr** [comment]
For now the README would be a place here. Later, when it's ready to get a DOI, e.g. on Figshare, we can have all of them as co-authors of the dataset
