### ISSUE TITLE
CrowdTangle: Neue Listen anlegen (Parlamentarier, Zeitungen, Nachrichtenredaktionen, Parteigliederungen)

### ISSUE THREAD

**Issue by grenwi** [Leibniz-HBI/DBoeS-Automatization#77]
- [x] reformat DBOES-Excel tables
- [x] create lists in CT dashboards
- [x] upload data
- [ ] handle errors
- [ ] reupload erroneous entries

**Comment by pekasen** [comment]
Done, lists are now available in dashboards for facebook and instagram, "dboes-fb` and `dboes-ig`, lists are named after the DBÖS type: 01 ,04, 09, 21 (as this was easier to generate adequate tables from the original data; we can rename the lists to a human readble name after corrections).
For both platforms we need to apply some corrections as some accounts are not available on crowdtangle.

**Comment by janhinrikschmidt** [comment]
@pekasen are we done with this task (and can we move it to "done")?
