### ISSUE TITLE
Twacapic: Restart der Sammlungen mit neuen Listen

### ISSUE THREAD

**Issue by grenwi** [Leibniz-HBI/DBoeS-Automatization#79]

**Comment by pekasen** [comment]
Collection now running on a testing server in the NOTORIOUS AWS Cloud with scalable file system.

**Comment by FlxVctr** [comment]
@pekasen So this can be closd?

**Comment by pekasen** [comment]
> @pekasen So this can be closd?

Yup. Collection and DB persistenace are running for Twitter.

**Comment by FlxVctr** [comment]
Thanks! Next time feel free to close right away :)
